# Generated by Django 2.1.2 on 2018-11-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Descriptions', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('Inprogress', 'Inprogress'), ('Completed', 'Completed'), ('Pending', 'Pending')], max_length=10)),
                ('visible_status', models.BooleanField(default=True)),
            ],
        ),
    ]
